blank_issues_enabled: false
contact_links:
  - name: Questions, Ideas, Discussions
    url: https://github.com/Data-Product-Business/open-data-product-spec/discussions
    about: Ask and answer questions, and propose new features.
